### ISSUE TITLE
No datasets, can not follow

### ISSUE THREAD

**Issue by SihengLi99** [NohTow/PPL-MCTS#2]

**Comment by NohTow** [comment]
Hi,

Since you did not provide much details, I'll try to guess what you are looking for.

If you are just trying to apply the method to your data, then the files can be whatever you want, you just need to define how to create prompts from this raw data.

If you are trying to reproduce the results of our paper, details about datasets/splits are given in the paper.
You can also directly find files used as prompts as well as weights at this link: [http://hoaxdetector.irisa.fr/data/PPL_MCTS_filetransfer.zip](http://hoaxdetector.irisa.fr/data/PPL_MCTS_filetransfer.zip)

Please see [#1](https://github.com/NohTow/PPL-MCTS/issues/1) for more details.

If it did not answer your questions, please give more details about what you are looking for.

**Comment by SihengLi99** [comment]
Sincerely thanks !
Wonderful job !
