### ISSUE TITLE
About the zipped dataset and model ckpts file.

### ISSUE THREAD

**Issue by Yuanhy1997** [NohTow/PPL-MCTS#3]
Really appreciate that you uploaded the datasets and model ckpts and im trying to reproduce your work.

But please add a kind reminder for that .zip file that it can not be extracted by 'unzip' while have to use '7z e'. This cause me lots of time to find out. 

Can you please separate the datasets and checkpoints files? and the directory structure inside the zip file is pretty confusing.

**Comment by Yuanhy1997** [comment]
BTW, I did not find the corresponding agnews data files and model ckpts in this zip file, can you please upload it?

**Comment by NohTow** [comment]
Hello,

Thanks for reaching out ! 

> But please add a kind reminder for that .zip file that it can not be extracted by 'unzip' while have to use '7z e'. This cause me lots of time to find out.

The compression has been done on Windows but I made sure it was extractable on Linux. I'll dig into that and surely create the zip file from a linux machine in order to prevent any difficulty.

> Can you please separate the datasets and checkpoints files? and the directory structure inside the zip file is pretty confusing.

You're right, having everything mixed there is not optimal, I'll try to make it so everyone can find and download only what they need easily. Unfortunately, it will be a bit delayed due to the owner of the server where are uploaded files being in vacation. I'll make sure this is done when he comes back (in addition to the newly .zip files).

> BTW, I did not find the corresponding agnews data files and model ckpts in this zip file, can you please upload it?

This is because ag_news have been used only in the SIGIR paper (https://github.com/NohTow/PPL-MCTS/tree/main/teammates).
The weights/data files from this paper have not been shared here (please note that the amazon_polarity files you have are from the NAACL paper, which are not the same). This was mostly because the SIGIR paper was more a proof of concept rather than SOTA models (c.f my comment on the readme : https://github.com/NohTow/PPL-MCTS/tree/main/teammates#language-models). But I should have shared these too, so here is a temporary link until I can upload them on the server: https://filesender.renater.fr/?s=download&token=321ed43c-95b6-4747-9d4b-7f3d8d617948
I used zip from Linux so it should be easier to unzip. Also, I packed every weights (bidirectionnal/unidirectionnal/generative discriminators) as well as train/val set for training the models and the prompts used for the generation. I cannot really separate each datasets/checkpoints right now (would require a lot of different links) but will do when I put them on the server.

**Comment by Yuanhy1997** [comment]
Thx for your reply!

For the experiments on the AG-news dataset i.e. your SIGIR paper, I am curious about the prompting tokens you used which are the prefix lines for generation. I think it would be nice that you release those prompts for other (including me) to follow your research.

**Comment by NohTow** [comment]
> prompting tokens you used which are the prefix lines for generation. 

I am not sure I understood correctly. If you are asking about what is exactly given as original input of the language model (hence, _prompts_) then as mentioned in the papers, it is either the "title" column for amazon_polarity or the first few tokens for every other dataset. 
The number of tokens kept as prompt should be specified in the papers, but in any case, the generation scripts already do the truncation to the size used in our experiments. (e.g for ag_news, the line `original_input = tokenizer(sot_texts, return_tensors="pt", padding=True, add_special_tokens=False, truncation=True, max_length=20).to("cuda")` only take the first 20 tokens). Making the generation script pointing towards the provided file should reproduce the experimental setup.

**Comment by Yuanhy1997** [comment]
Thx for your patience, wonderful work.
